### ISSUE TITLE
集成SDK

### ISSUE THREAD

**Issue by knight2010** [easemob/sdkexamples-ios#1]
*** First throw call stack:
(
	0   CoreFoundation                      0x03d771e4 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x0327c8e5 objc_exception_throw + 44
	2   CoreFoundation                      0x03e14243 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
	3   CoreFoundation                      0x03d6750b ___forwarding___ + 1019
	4   CoreFoundation                      0x03d670ee _CF_forwarding_prep_0 + 14
	5   CarCommunication                    0x0023fdab -[EMDeviceManager init] + 138
	6   CarCommunication                    0x0023fd07 __33+[EMDeviceManager sharedInstance]_block_invoke + 55
	7   libdispatch.dylib                   0x048b94d0 _dispatch_client_callout + 14
	8   libdispatch.dylib                   0x048a8e12 dispatch_once_f + 184
	9   libdispatch.dylib                   0x048a8d55 dispatch_once + 31
	10  CarCommunication                    0x0023fcbc +[EMDeviceManager sharedInstance] + 59
	11  CarCommunication                    0x0021a2be -[EaseMob deviceManager] + 55
	12  CarCommunication                    0x00219e60 -[EaseMob init] + 259
	13  CarCommunication                    0x00219d12 +[EaseMob sharedInstance] + 87
	14  CarCommunication                    0x0018c060 -[AppDelegate application:didFinishLaunchingWithOptions:] + 720
	15  UIKit                               0x01f3614f -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 309
	16  UIKit                               0x01f36aa1 -[UIApplication _callInitializationDelegatesForURL:payload:suspended:] + 1810
	17  UIKit                               0x01f3b667 -[UIApplication _runWithURL:payload:launchOrientation:statusBarStyle:statusBarHidden:] + 824
	18  UIKit                               0x01f4ff92 -[UIApplication handleEvent:withNewEvent:] + 3517
	19  UIKit                               0x01f50555 -[UIApplication sendEvent:] + 85
	20  UIKit                               0x01f3d250 _UIApplicationHandleEvent + 683
	21  GraphicsServices                    0x04701f02 _PurpleEventCallback + 776
	22  GraphicsServices                    0x04701a0d PurpleEventCallback + 46
	23  CoreFoundation                      0x03cf2ca5 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 53
	24  CoreFoundation                      0x03cf29db __CFRunLoopDoSource1 + 523
	25  CoreFoundation                      0x03d1d68c __CFRunLoopRun + 2156
	26  CoreFoundation                      0x03d1c9d3 CFRunLoopRunSpecific + 467
	27  CoreFoundation                      0x03d1c7eb CFRunLoopRunInMode + 123
	28  UIKit                               0x01f3ad9c -[UIApplication _run] + 840
	29  UIKit                               0x01f3cf9b UIApplicationMain + 1225
	30  CarCommunication                    0x001cbcfd main + 141
	31  libdyld.dylib                       0x04aed6d9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jifang1218** [comment]
seems you forgot to add -ObjC flag into linker. 
add -ObjC to "other link flags" in Xcode build settings.
